### ISSUE TITLE
[Emergency] 긴급 호출

### ISSUE THREAD

**Issue by JangDaljin** [twaun95/Signature#1]
⭐ Issue
`@SuppressLint("DrawAllocation")` 정리 바랍니다. 린트 데코레이터는 못 참죠 😅
놀러왔습니다 잘 지내시져?

**Comment by JangDaljin** [comment]
@twaun95 호출하기

**Comment by twaun95** [comment]
@JangDaljin 오 ㅋㅋㅋ 이제 봤어요. 코드 아직 많이 덜티 해요.. 어디까지 되나 시험해보고 있어서.. ㅋㅋㅋㅋ
